import type { Product } from '@/context/CartContext';

export const products: Product[] = [
  {
    id: 1,
    name: 'DRS Espresso',
    category: 'Espresso',
    price: 4.5,
    image: '/menu_espresso_turbo.png',
    description: 'High-speed caffeine kick for maximum overtake potential.',
    stats: { intensity: '98%', heat: '92°C' },
    color: 'red',
  },
  {
    id: 2,
    name: 'Apex Latte',
    category: 'Milk Based',
    price: 5.5,
    image: '/menu_latte_apex.png',
    description: 'Smooth transition from milk to coffee. Perfectly balanced.',
    stats: { intensity: '75%', heat: '85°C' },
    color: 'yellow',
  },
  {
    id: 3,
    name: 'Full Wet Cold Brew',
    category: 'Iced',
    price: 6.0,
    image: '/menu_cold_brew_wet.png',
    description: '18-hour slow infusion for maximum grip on long straights.',
    stats: { intensity: '85%', heat: '4°C' },
    color: 'blue',
  },
  {
    id: 4,
    name: 'Paddock Macchiato',
    category: 'Espresso',
    price: 4.8,
    image: '/menu_macchiato.png',
    description: 'Stained with elite milk foam. A legend in the pitlane.',
    stats: { intensity: '90%', heat: '90°C' },
    color: 'red',
  },
  {
    id: 5,
    name: 'Overcut Flat White',
    category: 'Milk Based',
    price: 5.8,
    image: '/menu_flat_white.png',
    description: 'Micro-foam precision that beats the competition.',
    stats: { intensity: '80%', heat: '88°C' },
    color: 'yellow',
  },
  {
    id: 6,
    name: 'Turbo Iced Americano',
    category: 'Iced',
    price: 5.2,
    image: '/menu_americano.png',
    description: 'Chilled performance that never loses momentum.',
    stats: { intensity: '70%', heat: '5°C' },
    color: 'blue',
  },
  {
    id: 7,
    name: 'APEX Team Cap',
    category: 'Merchandise',
    price: 35.0,
    image: '/merch_cap.png',
    description: 'Premium black racing cap with carbon fiber texture brim.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 8,
    name: 'Telemetry Thermal Mug',
    category: 'Merchandise',
    price: 28.5,
    image: '/merch_mug.png',
    description: 'Sleek matte black thermal coffee travel mug. Engineered to hold temperature.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 9,
    name: 'Paddock VIP Lanyard',
    category: 'Merchandise',
    price: 15.0,
    image: '/merch_lanyard.png',
    description: 'Official APEX BREWS paddock pass lanyard with premium weave.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 10,
    name: 'Carbon Espresso Cups',
    category: 'Merchandise',
    price: 45.0,
    image: '/merch_cups.png',
    description: 'Set of two ultra-lightweight polished carbon fiber espresso cups.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
];
