-- --------------------------------------------------------
-- APEX BREWS: SUPABASE DATABASE SCHEMA
-- --------------------------------------------------------
-- Execute this entire script in the Supabase SQL Editor.

-- 1. Create custom types
CREATE TYPE IF NOT EXISTS user_rank AS ENUM ('Rookie', 'Driver', 'Champion', 'Legend');

-- 2. Create the Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  avatar_url text,
  driver_rank user_rank DEFAULT 'Rookie'::user_rank,
  credits integer DEFAULT 0,
  xp integer DEFAULT 0,
  level integer DEFAULT 1,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. Create the Products table
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL,
  stock_count integer DEFAULT 0,
  category text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb, -- Store image URLs, printful variant IDs, etc.
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. Create the Orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status text DEFAULT 'pending',
  paypal_order_id text,
  total_amount numeric(10,2) NOT NULL,
  shipping_address jsonb,
  fulfillment_method text,
  customer_name text,
  customer_email text,
  customer_phone text,
  printful_order_id text,
  fulfillment_status text DEFAULT 'unfulfilled',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 5. Create the Order Items table
CREATE TABLE IF NOT EXISTS public.order_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(10,2) NOT NULL
);

-- --------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) SETUP
-- --------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can view and update their own profile
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Products: Anyone can read products, only admin (or bypass RLS) can edit
CREATE POLICY "Anyone can view products" ON public.products FOR SELECT USING (true);

-- Orders: Users can view their own orders
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
-- Insert orders is usually done by service_role (backend API) or we can allow authenticated users
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Order Items: Users can view items for their own orders
CREATE POLICY "Users can view own order items" ON public.order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.orders WHERE id = order_items.order_id AND user_id = auth.uid())
);

-- --------------------------------------------------------
-- TRIGGER: Auto-create Profile on Signup
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
