-- --------------------------------------------------------
-- APEX BREWS: SUPABASE DATABASE SCHEMA
-- --------------------------------------------------------
-- Execute this entire script in the Supabase SQL Editor.

-- 1. Create custom types
CREATE TYPE IF NOT EXISTS user_rank AS ENUM ('Rookie', 'Driver', 'Champion', 'Legend');

-- 2. Create the Profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  avatar_url text,
  driver_rank user_rank DEFAULT 'Rookie'::user_rank,
  credits integer DEFAULT 0,
  xp integer DEFAULT 0,
  level integer DEFAULT 1,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. Create the Products table
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  price numeric(10,2) NOT NULL,
  stock_count integer DEFAULT 0,
  category text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb, -- Store image URLs, printful variant IDs, etc.
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 4. Create the Orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status text DEFAULT 'pending',
  paypal_order_id text,
  total_amount numeric(10,2) NOT NULL,
  shipping_address jsonb,
  fulfillment_method text,
  customer_name text,
  customer_email text,
  customer_phone text,
  printful_order_id text,
  fulfillment_status text DEFAULT 'unfulfilled',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 5. Create the Order Items table
CREATE TABLE IF NOT EXISTS public.order_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(10,2) NOT NULL
);

-- --------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) SETUP
-- --------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can view and update their own profile
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Products: Anyone can read products, only admin (or bypass RLS) can edit
CREATE POLICY "Anyone can view products" ON public.products FOR SELECT USING (true);

-- Orders: Users can view their own orders
CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
-- Insert orders is usually done by service_role (backend API) or we can allow authenticated users
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Order Items: Users can view items for their own orders
CREATE POLICY "Users can view own order items" ON public.order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.orders WHERE id = order_items.order_id AND user_id = auth.uid())
);

-- --------------------------------------------------------
-- TRIGGER: Auto-create Profile on Signup
-- --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- --------------------------------------------------------
-- SEED DATA: PRODUCTS CATALOG
-- --------------------------------------------------------
INSERT INTO public.products (id, name, description, price, stock_count, category, metadata) VALUES
  (1, 'DRS Espresso', 'High-speed caffeine kick for maximum overtake potential.', 4.5, 100, 'Espresso', '{"image":"/menu_espresso_turbo.png","stats":{"intensity":"98%","heat":"92°C"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (2, 'Apex Latte', 'Smooth transition from milk to coffee. Perfectly balanced.', 5.5, 100, 'Milk Based', '{"image":"/menu_latte_apex.png","stats":{"intensity":"75%","heat":"85°C"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (3, 'Full Wet Cold Brew', '18-hour slow infusion for maximum grip on long straights.', 6, 100, 'Iced', '{"image":"/menu_cold_brew_wet.png","stats":{"intensity":"85%","heat":"4°C"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (4, 'Paddock Macchiato', 'Stained with elite milk foam. A legend in the pitlane.', 4.8, 100, 'Espresso', '{"image":"/menu_macchiato.png","stats":{"intensity":"90%","heat":"90°C"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (5, 'Overcut Flat White', 'Micro-foam precision that beats the competition.', 5.8, 100, 'Milk Based', '{"image":"/menu_flat_white.png","stats":{"intensity":"80%","heat":"88°C"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (6, 'Turbo Iced Americano', 'Chilled performance that never loses momentum.', 5.2, 100, 'Iced', '{"image":"/menu_americano.png","stats":{"intensity":"70%","heat":"5°C"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (7, 'Mercedes-AMG Petronas F1 Team Cap', 'Official Mercedes-AMG Petronas F1 Team Cap. Classic black with team logo.', 45, 100, 'Merchandise', '{"image":"/merch_cap.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (8, 'Williams Racing Thermal Mug', 'Official Williams Racing thermal coffee travel mug. Keeps your drinks hot on race day.', 30, 100, 'Merchandise', '{"image":"/merch_mug.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (9, 'Haas F1 Team Lanyard', 'Official Haas F1 Team paddock pass lanyard with premium weave.', 18, 100, 'Merchandise', '{"image":"/merch_lanyard.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (10, 'Kick Sauber F1 Espresso Cups', 'Set of two Kick Sauber F1 Team branded ceramic espresso cups.', 50, 100, 'Merchandise', '{"image":"/merch_cups.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (11, 'Red Bull Racing Team Hoodie', 'Official Red Bull Racing Team zip-up hoodie featuring sponsor logos and team colors.', 110, 100, 'Merchandise', '{"image":"/merch_hoodie.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (12, 'Scuderia Ferrari Team T-Shirt', 'Official Scuderia Ferrari Team T-Shirt in iconic Rosso Corsa.', 65, 100, 'Merchandise', '{"image":"/merch_tshirt.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (13, 'Alpine F1 Team Keychain', 'Premium metal keychain featuring the Alpine F1 Team logo.', 25, 100, 'Merchandise', '{"image":"/merch_keychain.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (14, 'Visa Cash App RB Driving Gloves', 'Official Visa Cash App RB branded leather driving gloves.', 85, 100, 'Merchandise', '{"image":"/merch_gloves.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (15, 'Aston Martin F1 Team Backpack', 'Official Aston Martin Aramco F1 Team backpack with ample storage and team branding.', 130, 100, 'Merchandise', '{"image":"/merch_backpack.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (16, 'McLaren F1 Team Water Bottle', 'Official McLaren F1 Team insulated aluminium water bottle in papaya orange.', 35, 100, 'Merchandise', '{"image":"/merch_bottle.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (17, 'Podium Red Velvet Cake', 'A rich, multi-layered red velvet cake worthy of the top step of the podium.', 8.5, 100, 'Pastries', '{"image":"/red_velvet_cake.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (18, 'Carbon Fiber Chocolate Fudge', 'Dark, dense chocolate fudge cake engineered for maximum flavor impact.', 7, 100, 'Pastries', '{"image":"/carbon_fiber_fudge.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (19, 'Telemetry Lemon Tart', 'A sharp, zesty lemon tart to refresh your palate between stints.', 6.5, 100, 'Pastries', '{"image":"/lemon_tart.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (20, 'V60 Slipstream Pour Over', 'Clean aerodynamic extraction utilizing a V60 filter. Smooth and bright.', 5.5, 100, 'Espresso', '{"image":"/menu_pour_over.png","stats":{"intensity":"60%","heat":"90°C"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (21, 'Formation Lap Frappe', 'Blended iced coffee to cool down the engines before lights out.', 6.5, 100, 'Iced', '{"image":"/menu_frappe.png","stats":{"intensity":"65%","heat":"0°C"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (22, 'Safety Car Mocha', 'Rich dark chocolate and espresso to keep you warm under the safety car.', 6, 100, 'Milk Based', '{"image":"/menu_mocha.png","stats":{"intensity":"75%","heat":"82°C"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (23, 'Quali-Lap Cortado', 'A short, punchy 1:1 ratio of espresso and milk for ultimate qualifying pace.', 4.5, 100, 'Espresso', '{"image":"/menu_cortado.png","stats":{"intensity":"95%","heat":"88°C"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (24, 'Interlagos Iced Tea', 'Refreshing Brazilian peach and lemon iced tea for those hot track days.', 4, 100, 'Iced', '{"image":"/menu_iced_tea.png","stats":{"intensity":"40%","heat":"2°C"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (25, 'Monaco Almond Croissant', 'A luxurious twice-baked almond croissant, a staple of the Riviera.', 4.5, 100, 'Pastries', '{"image":"/croissant.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (26, 'Silverstone Scone', 'Classic British scone served with clotted cream and strawberry jam.', 4, 100, 'Pastries', '{"image":"/scone.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (27, 'Suzuka Matcha Roll', 'Light and airy Japanese matcha sponge cake rolled with sweet cream.', 6.5, 100, 'Pastries', '{"image":"/matcha_roll.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (28, 'Pitlane Brownie Box', 'A box of three ultra-fudgy chocolate brownies for the whole mechanics crew.', 7.5, 100, 'Pastries', '{"image":"/brownie.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (29, 'Chequered Flag Cheesecake', 'New York style vanilla cheesecake topped with a black and white chocolate lattice.', 8, 100, 'Pastries', '{"image":"/cheesecake.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (30, 'Mercedes-AMG Petronas F1 Team Polo', 'A black Mercedes-AMG Petronas F1 Team polo shirt with neon teal accents.', 75, 100, 'Merchandise', '{"image":"/merch_mercedes_polo.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (31, 'Red Bull Racing Team Backpack', 'A navy blue Red Bull Racing F1 Team backpack with ample storage.', 95, 100, 'Merchandise', '{"image":"/merch_redbull_bag.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (32, 'Scuderia Ferrari F1 Team Umbrella', 'A bright red Scuderia Ferrari F1 Team umbrella to keep you dry on the pit wall.', 40, 100, 'Merchandise', '{"image":"/merch_ferrari_umbrella.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (33, 'McLaren F1 Team Sunglasses', 'Sleek, modern McLaren F1 Team sunglasses with papaya orange accents.', 120, 100, 'Merchandise', '{"image":"/merch_mclaren_glasses.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (34, 'Aston Martin Aramco F1 Jacket', 'Aston Martin Aramco F1 Team racing jacket in British Racing Green.', 150, 100, 'Merchandise', '{"image":"/merch_aston_jacket.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (35, 'Alpine F1 Team Beanie', 'A pink and blue Alpine F1 Team winter beanie hat.', 30, 100, 'Merchandise', '{"image":"/merch_alpine_beanie.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (36, 'Williams Racing Phone Case', 'Carbon fiber style Williams Racing phone case.', 25, 100, 'Merchandise', '{"image":"/merch_williams_case.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (37, 'Visa Cash App RB F1 Team Flag', 'Large racing flag with the Visa Cash App RB logo.', 20, 100, 'Merchandise', '{"image":"/merch_rb_flag.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (38, 'Kick Sauber F1 Team Mousepad', 'Kick Sauber F1 Team extra-large desk mat and mousepad.', 15, 100, 'Merchandise', '{"image":"/merch_sauber_mousepad.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (39, 'Haas F1 Team Coffee Mug', 'Ceramic Haas F1 Team coffee mug for your morning brews.', 22, 100, 'Merchandise', '{"image":"/merch_haas_mug.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (40, 'Pirelli P Zero Mini Tire Replica', 'Official Pirelli P Zero red soft compound miniature replica tire.', 60, 100, 'Merchandise', '{"image":"/merch_pirelli_tire.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (41, 'F1 Official VIP Pass Lanyard', 'F1 Official VIP Paddock Pass lanyard with premium quick-release.', 35, 100, 'Merchandise', '{"image":"/merch_lanyard.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (42, 'Monaco VIP Paddock Pass (Weekend)', 'Exclusive 3-day access to the Monaco Grand Prix Paddock Club. Meet the drivers, access the pit lane, and enjoy premium hospitality.', 12500, 100, 'Merchandise', '{"image":"/vip_monaco_pass.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":true,"requires_date":false,"fixed_date":"2026-05-24"}'::jsonb),
  (43, 'Aero Dynamics Factory Tour', 'A private guided tour of the Apex Brews aerodynamic coffee roasting facility and wind tunnel.', 1500, 100, 'Merchandise', '{"image":"/vip_aero_tour.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":true,"requires_date":true,"fixed_date":null}'::jsonb),
  (44, 'Silverstone GP VIP Ticket', 'Exclusive weekend pass to the Silverstone Grand Prix with full VIP Paddock access.', 1200, 100, 'Merchandise', '{"image":"/vip_silverstone.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":true,"requires_date":false,"fixed_date":"2026-07-05"}'::jsonb),
  (45, 'Spa-Francorchamps Hot Lap', 'Experience an unforgettable hot lap around Spa-Francorchamps in a 2-seater F1 car.', 2500, 100, 'Merchandise', '{"image":"/vip_spa_hot_lap.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":true,"requires_date":true,"fixed_date":null}'::jsonb),
  (46, 'Pit Wall Strategy Access', 'Sit on the pit wall during a live race simulation and listen to team radio comms.', 800, 100, 'Merchandise', '{"image":"/vip_pit_wall.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":true,"requires_date":true,"fixed_date":null}'::jsonb),
  (47, 'Apex Brews Carbon Tumbler', 'Premium carbon fiber thermal tumbler. Keeps coffee hot for 12 hours.', 45, 100, 'Merchandise', '{"image":"/merch_carbon_tumbler.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (48, 'Telemetry Energy Gel', 'A rapid-absorption sports energy gel with a strong espresso kick.', 12, 100, 'Pastries', '{"image":"/telemetry_gel.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (49, 'Tifosi Red Velvet Croissant', 'Vibrant red velvet croissant, filled with sweet mascarpone cream.', 6.5, 100, 'Pastries', '{"image":"/tifosi_croissant.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (50, 'Brake Dust Charcoal Latte', 'A striking black charcoal latte balanced with smooth oat milk and vanilla.', 6.8, 100, 'Milk Based', '{"image":"/brake_dust_latte.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"yellow","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (51, 'Ferrari Scuderia 44mm Chronograph Watch', 'Premium Ferrari Formula 1 silicone chronograph watch. Precision timing for the paddock.', 49.9, 100, 'Merchandise', '{"image":"/merch_ferrari_watch.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (52, 'Red Bull Racing Las Vegas Jacket', 'Official Red Bull F1 Team Las Vegas reflective night-race jacket.', 119.9, 100, 'Merchandise', '{"image":"/merch_vegas_jacket.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"blue","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb),
  (53, 'Charles Leclerc Monaco Pole Tyre Display', 'Exclusive 2024 Monaco Pole Position Pirelli Tyre replica. The ultimate collector piece.', 169.9, 100, 'Merchandise', '{"image":"/merch_pirelli_tire.png","stats":{"intensity":"N/A","heat":"N/A"},"color":"red","is_vip_only":false,"requires_date":false,"fixed_date":null}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  metadata = EXCLUDED.metadata;
