export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
  stats: {
    intensity: string;
    heat: string;
  };
  color: string;
  is_vip_only?: boolean;
  requires_date?: boolean;
  fixed_date?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: 'DRS Espresso',
    category: 'Espresso',
    price: 4.5,
    image: '/menu_espresso_turbo.png',
    description: 'High-speed caffeine kick for maximum overtake potential.',
    stats: { intensity: '98%', heat: '92°C' },
    color: 'red',
  },
  {
    id: 2,
    name: 'Apex Latte',
    category: 'Milk Based',
    price: 5.5,
    image: '/menu_latte_apex.png',
    description: 'Smooth transition from milk to coffee. Perfectly balanced.',
    stats: { intensity: '75%', heat: '85°C' },
    color: 'yellow',
  },
  {
    id: 3,
    name: 'Full Wet Cold Brew',
    category: 'Iced',
    price: 6.0,
    image: '/menu_cold_brew_wet.png',
    description: '18-hour slow infusion for maximum grip on long straights.',
    stats: { intensity: '85%', heat: '4°C' },
    color: 'blue',
  },
  {
    id: 4,
    name: 'Paddock Macchiato',
    category: 'Espresso',
    price: 4.8,
    image: '/menu_macchiato.png',
    description: 'Stained with elite milk foam. A legend in the pitlane.',
    stats: { intensity: '90%', heat: '90°C' },
    color: 'red',
  },
  {
    id: 5,
    name: 'Overcut Flat White',
    category: 'Milk Based',
    price: 5.8,
    image: '/menu_flat_white.png',
    description: 'Micro-foam precision that beats the competition.',
    stats: { intensity: '80%', heat: '88°C' },
    color: 'yellow',
  },
  {
    id: 6,
    name: 'Turbo Iced Americano',
    category: 'Iced',
    price: 5.2,
    image: '/menu_americano.png',
    description: 'Chilled performance that never loses momentum.',
    stats: { intensity: '70%', heat: '5°C' },
    color: 'blue',
  },
  {
    id: 7,
    name: 'Mercedes-AMG Petronas F1 Team Cap',
    category: 'Merchandise',
    price: 45.0,
    image: '/merch_cap.png',
    description: 'Official Mercedes-AMG Petronas F1 Team Cap. Classic black with team logo.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 8,
    name: 'Williams Racing Thermal Mug',
    category: 'Merchandise',
    price: 30.0,
    image: '/merch_mug.png',
    description: 'Official Williams Racing thermal coffee travel mug. Keeps your drinks hot on race day.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 9,
    name: 'Haas F1 Team Lanyard',
    category: 'Merchandise',
    price: 18.0,
    image: '/merch_lanyard.png',
    description: 'Official Haas F1 Team paddock pass lanyard with premium weave.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 10,
    name: 'Kick Sauber F1 Espresso Cups',
    category: 'Merchandise',
    price: 50.0,
    image: '/merch_cups.png',
    description: 'Set of two Kick Sauber F1 Team branded ceramic espresso cups.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 11,
    name: 'Red Bull Racing Team Hoodie',
    category: 'Merchandise',
    price: 110.0,
    image: '/merch_hoodie.png',
    description: 'Official Red Bull Racing Team zip-up hoodie featuring sponsor logos and team colors.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 12,
    name: 'Scuderia Ferrari Team T-Shirt',
    category: 'Merchandise',
    price: 65.0,
    image: '/merch_tshirt.png',
    description: 'Official Scuderia Ferrari Team T-Shirt in iconic Rosso Corsa.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 13,
    name: 'Alpine F1 Team Keychain',
    category: 'Merchandise',
    price: 25.0,
    image: '/merch_keychain.png',
    description: 'Premium metal keychain featuring the Alpine F1 Team logo.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 14,
    name: 'Visa Cash App RB Driving Gloves',
    category: 'Merchandise',
    price: 85.0,
    image: '/merch_gloves.png',
    description: 'Official Visa Cash App RB branded leather driving gloves.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 15,
    name: 'Aston Martin F1 Team Backpack',
    category: 'Merchandise',
    price: 130.0,
    image: '/merch_backpack.png',
    description: 'Official Aston Martin Aramco F1 Team backpack with ample storage and team branding.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 16,
    name: 'McLaren F1 Team Water Bottle',
    category: 'Merchandise',
    price: 35.0,
    image: '/merch_bottle.png',
    description: 'Official McLaren F1 Team insulated aluminium water bottle in papaya orange.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 17,
    name: 'Podium Red Velvet Cake',
    category: 'Pastries',
    price: 8.5,
    image: '/red_velvet_cake.png',
    description: 'A rich, multi-layered red velvet cake worthy of the top step of the podium.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 18,
    name: 'Carbon Fiber Chocolate Fudge',
    category: 'Pastries',
    price: 7.0,
    image: '/carbon_fiber_fudge.png',
    description: 'Dark, dense chocolate fudge cake engineered for maximum flavor impact.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 19,
    name: 'Telemetry Lemon Tart',
    category: 'Pastries',
    price: 6.5,
    image: '/lemon_tart.png',
    description: 'A sharp, zesty lemon tart to refresh your palate between stints.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 20,
    name: 'V60 Slipstream Pour Over',
    category: 'Espresso',
    price: 5.5,
    image: '/menu_pour_over.png',
    description: 'Clean aerodynamic extraction utilizing a V60 filter. Smooth and bright.',
    stats: { intensity: '60%', heat: '90°C' },
    color: 'red',
  },
  {
    id: 21,
    name: 'Formation Lap Frappe',
    category: 'Iced',
    price: 6.5,
    image: '/menu_frappe.png',
    description: 'Blended iced coffee to cool down the engines before lights out.',
    stats: { intensity: '65%', heat: '0°C' },
    color: 'blue',
  },
  {
    id: 22,
    name: 'Safety Car Mocha',
    category: 'Milk Based',
    price: 6.0,
    image: '/menu_mocha.png',
    description: 'Rich dark chocolate and espresso to keep you warm under the safety car.',
    stats: { intensity: '75%', heat: '82°C' },
    color: 'yellow',
  },
  {
    id: 23,
    name: 'Quali-Lap Cortado',
    category: 'Espresso',
    price: 4.5,
    image: '/menu_cortado.png',
    description: 'A short, punchy 1:1 ratio of espresso and milk for ultimate qualifying pace.',
    stats: { intensity: '95%', heat: '88°C' },
    color: 'red',
  },
  {
    id: 24,
    name: 'Interlagos Iced Tea',
    category: 'Iced',
    price: 4.0,
    image: '/menu_iced_tea.png',
    description: 'Refreshing Brazilian peach and lemon iced tea for those hot track days.',
    stats: { intensity: '40%', heat: '2°C' },
    color: 'blue',
  },
  {
    id: 25,
    name: 'Monaco Almond Croissant',
    category: 'Pastries',
    price: 4.5,
    image: '/croissant.png',
    description: 'A luxurious twice-baked almond croissant, a staple of the Riviera.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 26,
    name: 'Silverstone Scone',
    category: 'Pastries',
    price: 4.0,
    image: '/scone.png',
    description: 'Classic British scone served with clotted cream and strawberry jam.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 27,
    name: 'Suzuka Matcha Roll',
    category: 'Pastries',
    price: 6.5,
    image: '/matcha_roll.png',
    description: 'Light and airy Japanese matcha sponge cake rolled with sweet cream.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 28,
    name: 'Pitlane Brownie Box',
    category: 'Pastries',
    price: 7.5,
    image: '/brownie.png',
    description: 'A box of three ultra-fudgy chocolate brownies for the whole mechanics crew.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 29,
    name: 'Chequered Flag Cheesecake',
    category: 'Pastries',
    price: 8.0,
    image: '/cheesecake.png',
    description: 'New York style vanilla cheesecake topped with a black and white chocolate lattice.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 30,
    name: 'Mercedes-AMG Petronas F1 Team Polo',
    category: 'Merchandise',
    price: 75.0,
    image: '/merch_mercedes_polo.png',
    description: 'A black Mercedes-AMG Petronas F1 Team polo shirt with neon teal accents.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 31,
    name: 'Red Bull Racing Team Backpack',
    category: 'Merchandise',
    price: 95.0,
    image: '/merch_redbull_bag.png',
    description: 'A navy blue Red Bull Racing F1 Team backpack with ample storage.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 32,
    name: 'Scuderia Ferrari F1 Team Umbrella',
    category: 'Merchandise',
    price: 40.0,
    image: '/merch_ferrari_umbrella.png',
    description: 'A bright red Scuderia Ferrari F1 Team umbrella to keep you dry on the pit wall.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 33,
    name: 'McLaren F1 Team Sunglasses',
    category: 'Merchandise',
    price: 120.0,
    image: '/merch_mclaren_glasses.png',
    description: 'Sleek, modern McLaren F1 Team sunglasses with papaya orange accents.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 34,
    name: 'Aston Martin Aramco F1 Jacket',
    category: 'Merchandise',
    price: 150.0,
    image: '/merch_aston_jacket.png',
    description: 'Aston Martin Aramco F1 Team racing jacket in British Racing Green.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 35,
    name: 'Alpine F1 Team Beanie',
    category: 'Merchandise',
    price: 30.0,
    image: '/merch_alpine_beanie.png',
    description: 'A pink and blue Alpine F1 Team winter beanie hat.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 36,
    name: 'Williams Racing Phone Case',
    category: 'Merchandise',
    price: 25.0,
    image: '/merch_williams_case.png',
    description: 'Carbon fiber style Williams Racing phone case.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 37,
    name: 'Visa Cash App RB F1 Team Flag',
    category: 'Merchandise',
    price: 20.0,
    image: '/merch_rb_flag.png',
    description: 'Large racing flag with the Visa Cash App RB logo.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 38,
    name: 'Kick Sauber F1 Team Mousepad',
    category: 'Merchandise',
    price: 15.0,
    image: '/merch_sauber_mousepad.png',
    description: 'Kick Sauber F1 Team extra-large desk mat and mousepad.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 39,
    name: 'Haas F1 Team Coffee Mug',
    category: 'Merchandise',
    price: 22.0,
    image: '/merch_haas_mug.png',
    description: 'Ceramic Haas F1 Team coffee mug for your morning brews.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 40,
    name: 'Pirelli P Zero Mini Tire Replica',
    category: 'Merchandise',
    price: 60.0,
    image: '/merch_pirelli_tire.png',
    description: 'Official Pirelli P Zero red soft compound miniature replica tire.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 41,
    name: 'F1 Official VIP Pass Lanyard',
    category: 'Merchandise',
    price: 35.0,
    image: '/merch_lanyard.png',
    description: 'F1 Official VIP Paddock Pass lanyard with premium quick-release.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 42,
    name: 'Monaco VIP Paddock Pass (Weekend)',
    category: 'Merchandise',
    price: 12500.0,
    image: '/vip_monaco_pass.png',
    description: 'Exclusive 3-day access to the Monaco Grand Prix Paddock Club. Meet the drivers, access the pit lane, and enjoy premium hospitality.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
    is_vip_only: true,
    fixed_date: '2026-05-24',
  },
  {
    id: 43,
    name: 'Aero Dynamics Factory Tour',
    category: 'Merchandise',
    price: 1500.0,
    image: '/vip_aero_tour.png',
    description: 'A private guided tour of the Apex Brews aerodynamic coffee roasting facility and wind tunnel.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
    is_vip_only: true,
    requires_date: true,
  },
  {
    id: 44,
    name: 'Silverstone GP VIP Ticket',
    category: 'Merchandise',
    price: 1200.0,
    image: '/vip_silverstone.png',
    description: 'Exclusive weekend pass to the Silverstone Grand Prix with full VIP Paddock access.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
    is_vip_only: true,
    fixed_date: '2026-07-05',
  },
  {
    id: 45,
    name: 'Spa-Francorchamps Hot Lap',
    category: 'Merchandise',
    price: 2500.0,
    image: '/vip_spa_hot_lap.png',
    description: 'Experience an unforgettable hot lap around Spa-Francorchamps in a 2-seater F1 car.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
    is_vip_only: true,
    requires_date: true,
  },
  {
    id: 46,
    name: 'Pit Wall Strategy Access',
    category: 'Merchandise',
    price: 800.0,
    image: '/vip_pit_wall.png',
    description: 'Sit on the pit wall during a live race simulation and listen to team radio comms.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
    is_vip_only: true,
    requires_date: true,
  },
  {
    id: 47,
    name: 'Apex Brews Carbon Tumbler',
    category: 'Merchandise',
    price: 45.0,
    image: '/merch_carbon_tumbler.png',
    description: 'Premium carbon fiber thermal tumbler. Keeps coffee hot for 12 hours.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 48,
    name: 'Telemetry Energy Gel',
    category: 'Pastries',
    price: 12.0,
    image: '/telemetry_gel.png',
    description: 'A rapid-absorption sports energy gel with a strong espresso kick.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 49,
    name: 'Tifosi Red Velvet Croissant',
    category: 'Pastries',
    price: 6.5,
    image: '/tifosi_croissant.png',
    description: 'Vibrant red velvet croissant, filled with sweet mascarpone cream.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 50,
    name: 'Brake Dust Charcoal Latte',
    category: 'Milk Based',
    price: 6.8,
    image: '/brake_dust_latte.png',
    description: 'A striking black charcoal latte balanced with smooth oat milk and vanilla.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'yellow',
  },
  {
    id: 51,
    name: 'Ferrari Scuderia 44mm Chronograph Watch',
    category: 'Merchandise',
    price: 49.90,
    image: '/merch_ferrari_watch.png',
    description: 'Premium Ferrari Formula 1 silicone chronograph watch. Precision timing for the paddock.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  },
  {
    id: 52,
    name: 'Red Bull Racing Las Vegas Jacket',
    category: 'Merchandise',
    price: 119.90,
    image: '/merch_vegas_jacket.png',
    description: 'Official Red Bull F1 Team Las Vegas reflective night-race jacket.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'blue',
  },
  {
    id: 53,
    name: 'Charles Leclerc Monaco Pole Tyre Display',
    category: 'Merchandise',
    price: 169.90,
    image: '/merch_pirelli_tire.png',
    description: 'Exclusive 2024 Monaco Pole Position Pirelli Tyre replica. The ultimate collector piece.',
    stats: { intensity: 'N/A', heat: 'N/A' },
    color: 'red',
  }
];
